# Generated by Django 4.2.1 on 2023-05-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('ext_number', models.CharField(blank=True, max_length=255, null=True)),
                ('phone1', models.CharField(blank=True, max_length=14, null=True)),
                ('phone2', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website_link', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_link', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=255, null=True)),
                ('tiktok_link', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=255, null=True)),
                ('zoom_link', models.CharField(blank=True, max_length=255, null=True)),
                ('teams_link', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=255, null=True)),
                ('gmail_link', models.CharField(blank=True, max_length=255, null=True)),
                ('outlook_link', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('map_link', models.CharField(max_length=100)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('qr_code', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
