# Generated by Django 4.2.1 on 2023-05-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Messaanger_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedIn_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
