# Generated by Django 4.2.1 on 2023-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManager', '0002_contact_messaanger_link_contact_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
